### ISSUE TITLE
Just two small tweak idears

### ISSUE THREAD

**Issue by MysticEmpires** [MysticRyuujin/guac-install#11]
Hi,

first at all i love the script. No big problems just two small tweak idears :)

# 1.Upgrade more then one "upgrade-pre-0.9.11.sql"

The `guac-update.sh` would just execute the last `upgrade-pre-x.sql`. This is fine as long as u upgrade from the lastest version.

But what if u are do an bigger version jump as example from 0.9.10 to 0.9.13. U would need to execute `upgrade-pre-0.9.11.sql` and `upgrade-pre-0.9.13.sql`. So i guess it would be an good idear to read the current-version before upgrading and later use this version to found the .sql that are needed to be executed.

# ~~2. Variable for"tomcat8"~~

~~Maybe it would also an good idear to but "tomcat8" in an var. Just for an better Update preparation :)~~

**Comment by MysticRyuujin** [comment]
For number one, I'm all for it, however there really isn't a simple way to find out what current version someone is running... I submitted a feature request to Guacamole to add a version parameter to the guacd executable. If you can come up with a surefire way to get current version I'm game to include it.

For number two, is this to support tomcat 7 or something? I'm only concerned because I haven't tested with anything but tomcat 8 and I'm not sure what other changes would be required?

And thanks for the commit to fix #3!

**Comment by MysticEmpires** [comment]
For number one: Actual not. I hope u have an idear :(

For number two: Would be an example. At my research i found this:

http://chari.titanium.ee/script-to-install-guacamole/

ok i would change the check, because it would not fit for `stretch`, as example. But at all it would make it a bit more generic. Maybe there is also an sweet way to get the `tomcat8` dynamic. But im not digging deeper into it.

**Comment by MysticRyuujin** [comment]
Alright, so I added some logic to check apt-cache to get the latest available between 8,7, and 6 when installing...and a commented line to set whatever you want... outside of Tomcat though I'm not automating that :) I added a variable in the upgrade script too to make that simpler for someone not running tomcat8

**Comment by MysticEmpires** [comment]
That seems valid for me :) (still Strikethrough the first part in the first post).

Btw. i will test the script on Pi (Raspian) this weekend so maybe i found something more :)

**Comment by MysticRyuujin** [comment]
Feel free to open a new Issue if you feel like more work should be done :)
