### ISSUE TITLE
RDP not fully working on Windows 10 Pro Build 1909.

### ISSUE THREAD

**Issue by IPxK** [MysticRyuujin/guac-install#118]
Hi,

I was wondering if anyone else have an issue when they RDP into a Windows 10 Pro/Home machine?
At first it wouldn't connect at all to the computer and it kept telling me the guacamole server couldn't connect so I found out I had to go into the registry and change the Security Layer and UserAuthentication. That allowed me to connect and get into the computer via RDP but then the connection disconnect by itself. I look at the syslog and it didn't throw out any error messages except the standard user disconnect. I tried the same attempt on a AWS EC2 running Windows Server 2019 and I did not have this issue. Windows 7 machines works fine with no needed altercation in the registry. I'm running the current up to date version of Guacamole that is on this Github.

**Comment by MysticRyuujin** [comment]
Can you clarify? You cannot RDP into a Home machine. See #89

**Comment by IPxK** [comment]
I installed Guac on Ubuntu Server 18.04.4.

**Comment by IPxK** [comment]
I did go through the basic troubleshooting before and it didn't help. So maybe it is a bug related to the FreeRDP2 and Guac 1.1.0 with the current build of Windows 10 Pro 1909.

**Comment by tsinalis** [comment]
Same here, tried step-by-step troubleshooting several times, ended up installing Guac 1.0.0, works flawless.

**Comment by MysticRyuujin** [comment]
Guac 1.0.0 still uses freerdp2 not freerdp2. I assume you're both using Ubuntu 18.04?

**Comment by tsinalis** [comment]
Ubuntu 18.04 is right, xfreerdp /version gives me 2.0.0-dev. And I just realized I was wrong about Guac 1.0.0, apt gives me 0.9.9+dfsg-1; after it did not work with 1.1.0 I stepped down version by version until it did (admitting I'm a little bit of a noob)

**Comment by phuongpham** [comment]
I can confirm the same issue. I have tried to connect to different win10 1909 machine and get samme issue. I get diconnected straight after connecting to the machine. When checking syslog I see follow error: 

Mar 11 11:45:30 guacamole kernel: [  228.127774] guacd[18515]: segfault at 0 ip 0000000000000000 sp 00007f3b137fdb18 error 14 in guacd[55793e034000+7000]
Mar 11 11:45:30 guacamole kernel: [  228.127779] Code: Bad RIP value.

**Comment by IPxK** [comment]
Did anyone find a fix for this issue or is the solution just going back to the previous version for the time being?

**Comment by graham00** [comment]
I had exactly the same issue just now on a fresh install with Ubuntu 18.04.4 LTS.

I fixed it by removing freerdp2 and compiling it from source with the latest freerdp2 release (rc4, which, amazingly, is from all the way back in 2018 so the Ubuntu freerdp2 must be really old...).

Here are the steps I followed:

`
apt-get remove freerdp2-dev freerdp2-x11 libfreerdp-client2-2 libfreerdp-shadow-subsystem2-2 libfreerdp-shadow2-2 libfreerdp2-2
dpkg -l | grep freerdp
# ^ if any freerdp packages are still left, remove those too
# https://github.com/FreeRDP/FreeRDP/releases
wget https://github.com/FreeRDP/FreeRDP/archive/2.0.0-rc4.tar.gz
mv 2.0.0-rc4.tar.gz freerdp2.0.0-rc4.tar.gz
tar zxfv freerdp2.0.0-rc4.tar.gz
cd FreeRDP-2.0.0-rc4/
# https://github.com/FreeRDP/FreeRDP/wiki/Compilation
apt-get install ninja-build build-essential git-core debhelper cdbs dpkg-dev autotools-dev cmake pkg-config xmlto libssl-dev docbook-xsl xsltproc libxkbfile-dev libx11-dev libwayland-dev libxrandr-dev libxi-dev libxrender-dev libxext-dev libxinerama-dev libxfixes-dev libxcursor-dev libxv-dev libxdamage-dev libxtst-dev libcups2-dev libpcsclite-dev libasound2-dev libpulse-dev libjpeg-dev libgsm1-dev libusb-1.0-0-dev libudev-dev libdbus-glib-1-dev uuid-dev libxml2-dev libgstreamer1.0-dev libgstreamer0.10-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-base0.10-dev libfaad-dev libfaac-dev
    # had error finding that gstreamer version...
dpkg -l | grep gstream
    #...apparently newer version already installed so cut those out..
apt-get install ninja-build build-essential git-core debhelper cdbs dpkg-dev autotools-dev cmake pkg-config xmlto libssl-dev docbook-xsl xsltproc libxkbfile-dev libx11-dev libwayland-dev libxrandr-dev libxi-dev libxrender-dev libxext-dev libxinerama-dev libxfixes-dev libxcursor-dev libxv-dev libxdamage-dev libxtst-dev libcups2-dev libpcsclite-dev libasound2-dev libpulse-dev libjpeg-dev libgsm1-dev libusb-1.0-0-dev libudev-dev libdbus-glib-1-dev uuid-dev libxml2-dev libfaad-dev libfaac-dev
# install optional dependencies:
apt-get install libcunit1-dev libdirectfb-dev xmlto doxygen libxtst-dev
# other deps I found I needed:
apt-get install libsystemd-dev
#apt-get install libclang-dev
    # I think all I needed was actually this next one instead...if things don't work out for you though then maybe run this though.
apt-get remove clang-format
apt-get install clang-format-9
ln -s /usr/bin/clang-format-9 /usr/bin/clang-format
cmake -GNinja -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON -DWITH_CUPS=ON -DWITH_PULSE=ON -DWITH_FAAC=ON -DWITH_FAAD2=ON -DWITH_GSM=ON -DWITH_CAIRO=ON . > z
cmake --build .
cmake --build . --target install
# Now to upgrade guacamole-server with a new compile linked against the new freerdp lib:
# (since we're not switching versions, we don't need to do a lot of what the normal upgrade script does, so here are just the commands needed):
GUACVERSION="1.1.0"
SERVER="http://apache.org/dyn/closer.cgi?action=download&filename=guacamole/${GUACVERSION}"
wget -q --show-progress -O guacamole-server-${GUACVERSION}.tar.gz ${SERVER}/source/guacamole-server-${GUACVERSION}.tar.gz
tar -xzf guacamole-server-${GUACVERSION}.tar.gz
cd guacamole-server-${GUACVERSION}
./configure --with-init-dir=/etc/init.d
make
make install
ldconfig
systemctl enable guacd
`

**Comment by MysticRyuujin** [comment]
Is it worth the effort to make a script that patches FreeRDP using your work above? Idk how hard it would be to script that?

**Comment by graham00** [comment]
Ehhh...probably not, honestly, since I suspect way too much could vary to script that out effectively across a lot of systems that might be running slightly different builds of 18.04, and/or have just installed other stuff at different points and might run into unanticipated differences.

Might be better to just update the front page with a recommendation to use Debian for a new deployment at present instead of Ubuntu until Ubuntu updates their freerdp2 package. I don't know for a fact that Debian would be any better, but it looks like theirs is built on a significantly newer snapshot of FreeRDP (2019) so odds are probably better:

https://packages.debian.org/search?keywords=freerdp2

**Comment by MysticRyuujin** [comment]
Has anyone tried the PPA?

It might be a workaround to just add the PPA before running the script.

https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/freerdp-daily

sudo add-apt-repository ppa:remmina-ppa-team/freerdp-daily
sudo apt-get update

**Comment by phuongpham** [comment]
I can confirm that it works fine now!
Thanks for the great work everyone!

**Comment by florentlagoda** [comment]
> Has anyone tried the PPA?
> 
> It might be a workaround to just add the PPA before running the script.
> 
> https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/freerdp-daily
> 
> ```
> sudo add-apt-repository ppa:remmina-ppa-team/freerdp-daily
> sudo apt-get update
> ```
> 
> If you guys already have a broken install you can test it by then just running this after the above:
> `sudo apt-get install freerdp2-dev freerdp2-x11`
> 
> For me, this seems to have helped, I can right click on the start menu without it crashing now...

Hi,
How to do this on Debian 10 Buster ?
I have this error :
`softwareproperties.shortcuts.ShortcutException: Cannot add PPA: 'ppa:~remmina-ppa-team/ubuntu/freerdp-daily'.
ERROR: '~remmina-ppa-team' user or team does not exist.
Error: 'ppa:remmina-ppa-team/freerdp-daily' invalid
`

**Comment by go-ten** [comment]
Hello,

Try to disable WDDM in Windows 10.
