### ISSUE TITLE
Having Due on guac docker version

### ISSUE THREAD

**Issue by LightMoon** [MysticRyuujin/guac-install#174]
Hi,

wondering if your script support having the due extension enabled on the docker version of guac?

What I want to achieve to have Guac integrated with due, letsencrypt and Nginx, not sure which script suits me best

**Comment by MysticRyuujin** [comment]
The script doesn't directly support it, but you can extract the extension into the extension folder, mount a guacamole.properties etc.

The script would get you up and running, you'd have to add the duo part.

If I get around to it, I'll look at additional options for the docker script.

**Comment by Docop2** [comment]
There is lot of other docker stuff for temporary stuff around. Your script is perfect as is. thanks

**Comment by MysticRyuujin** [comment]
FYI - I updated the docker version to support TOTP...I did not do DUO because I don't have a way to test it - however, the new setup should make it WAY easier for you to add it.

The new version creates persistent storage under `/opt/guacamole/` (by default, you can change this) and that then allows you to add the duo jar file to `/opt/guacamole/extensions/` and create the `guacamole.properties` in `/opt/guacamole/` - and it should work if you do those 2 things...
