### ISSUE TITLE
Upgrade script doesn't update guacd

### ISSUE THREAD

**Issue by HerrFrodo** [MysticRyuujin/guac-install#271]
Hello together, 

I'm currently facing a problem after upgrading to 1.5.4 from 1.5.3.
In the syslog I get the following error

`Apr  2 21:00:04 guacamole guacd[709]: free(): double free detected in tcache 2`

After checking the guacd Version, I can see that it's still 1.5.3. I'm not sure if these two problems are related. 
Nevertheless, the script seems to not update guacd.

**Comment by anarchydude** [comment]
You might want to try the solution in #269 . I had the same issue on Debian 11, and now with the upgrade to 1.5.5, I was able to upgrade and get the correct guacd version.

**Comment by itiligent** [comment]
Yes, this was a 1.5.4 bug, it was fixed in 1.5.5. I updated my repo build script with a workaround for this bug and I will leave it in there in case people want to build or revert to 1.5.4 for any reason.
[https://github.com/itiligent/Guacamole-Install](https://github.com/itiligent/Guacamole-Install)

**Comment by HerrFrodo** [comment]
I build the Server from Source, which led to an error of guacd not finding a shared library. I than updated to Debian 12, and it worked. I had to replace the .war file, but apart from that it was straightforward.
