### ISSUE TITLE
Idea: Enable Arguments for Guac-Install.sh

### ISSUE THREAD

**Issue by bigredthelogger** [MysticRyuujin/guac-install#36]
It would be great to be able to call this script from an Azure Resource Manager template. Would it be possible to extend the script to allow arguments to be specified for the following:
- MySQL Root Password
- Guacamole DB Name
- Guacamole DB User
- Guacamole DB User Password

This would allow a Custom Script Extension to be added to an Azure Virtual machine which fully automates the installation of Apache Guacamole with user defined arguments.

**Comment by MysticRyuujin** [comment]
I like the idea, I don't have much time to actually do it though... I'm open to pull requests 👍

**Comment by bigredthelogger** [comment]
I am learning about Azure Resource Manager templates and wanted to execute your script to install Guacamole without any interaction. I figured out how to make the required changes in Bash. However, I have never used Git, so I have no idea what or how to make a Pull Request. I've attached the file if that works?
[guac-install.txt](https://github.com/MysticRyuujin/guac-install/files/1798474/guac-install.txt)

**Comment by bigredthelogger** [comment]
Thanks. One more suggestion (I am going to learn how to use GitHub so this is easier over the weekend).

Line 7: apt update generates this warning:
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
This should be changed to: apt-get update

**Comment by MysticRyuujin** [comment]
So I can switch to apt-get but then you loose the progress bar, given the fact that I don't do any processing of the output or care if the output changes (beyond successfully installing) it's not really that important.

It's essentially a non-issue unless someone wants to script around the apt commands outputs, which I suppose someone could want to that at some point. I just use apt because it's pretty :)

If you figure out how to submit a pull request to update it, I'll merge it because I don't care haha

**Comment by bigredthelogger** [comment]
Alright. In case your interested, I posted my finish product here. It includes Nginx-install.sh which automates a proxy and free SSL certificate which might be of benefit to your script. I am going to watch some videos on GitHub soon.

https://github.com/bigredthelogger/guacamole
