### ISSUE TITLE
Windows Client

### ISSUE THREAD

**Issue by schmidiij** [MysticRyuujin/guac-install#51]
Your script is awsom!

i install it on a Ubuntu Server 18.04 LTS and it's run.
But i haved problem with the Windows Clients - it will not connect
(Connect over SSH to a Linux client works fin)

i try on the guacamole Server telnet to the Windows Client:
![image](https://user-images.githubusercontent.com/29889802/46135754-35bedc00-c246-11e8-90db-48e832b7f7c0.png)
and this work

my Config is:
![image](https://user-images.githubusercontent.com/29889802/46135795-54bd6e00-c246-11e8-84e7-b805f9f42596.png)

not more, where is here the Problem?

**Comment by MysticRyuujin** [comment]
What does "Jede" mean?

In order to RRDP to a windows machine you need a few things:

1. It has to be a Pro or Enterprise system, Windows Home editions cannot be RDP into (from is ok, not to)
2. You must have RDP enabled, including the firewall rules that allow it
3. You must be a user who is allowed to use RFP into that machine

If 1-3 are correct then you should be able RDP to the system from another Windows System...you can do all of that and it's still not working then it's probably:

1. Encryption method (Usually this would be NLA)
2. Disable Server Certificate Check (I think you already did this)
3. Include the username/password/domain in the config

I could be wrong, it's been a long time since I've messed around with it, but I don't think you can NOT pass the credentials in the connection request. I think the good old days of making the RDP connection first, and being prompted for the credentials is gone. Of course there's probably something you can configure to restore that but I'm too lazy to look into it.

Let me know if that helps?

**Comment by Xyvir** [comment]
There is actually a potentially ToS breaking way around the limitation of needing Windows Pro.

There is a software out there called RDP Wrapper that allows you to RPD into Home editions of windows.

https://github.com/stascorp/rdpwrap/

I would suggest only using this for home-lab or testing type scenarios.

-Tyler

**Comment by la0wei** [comment]
I met the same problom,can't connet to windows,linux haven't have a try.
I use caddy(https://caddyserver.com) as a reverse proxy,for guacamole is runing on localhost,I want to make it public access and tls encryption later.
I just use caddy proxy 80 to 8080 on localhost.

just got this
![ip](https://user-images.githubusercontent.com/3761308/57188595-b576fc80-6f33-11e9-96bf-5a22a30073e3.png)
![h](https://user-images.githubusercontent.com/3761308/57188597-bdcf3780-6f33-11e9-8bc5-c9907e1c8261.png)

it didn't connect to the right ip address.
