### ISSUE TITLE
ERROR o.a.g.s.GuacamoleHTTPTunnelServlet with guac-install 1.0.0

### ISSUE THREAD

**Issue by m4xx75** [MysticRyuujin/guac-install#72]
Hello,

I encounter an error after a fresh install of 1.0.0 on Ubuntu server 18.04.1 :

```
11:36:06.241 [http-nio-8080-exec-1] ERROR o.a.g.s.GuacamoleHTTPTunnelServlet - HTTP tunnel request failed: java.net.ConnectException: Connection refused (Connection refused)
```

Thanks in advance,
maxx

**Comment by m4xx75** [comment]
up

**Comment by MysticRyuujin** [comment]
Post log in /tmp/

**Comment by m4xx75** [comment]
II found the solution.

It is necessary to fix Hostname and port of guacamole proxy in guacamole.proporties:
```
guacd-hostname: 127.0.0.1
guacd-port:     4822
```
I close.
maxx

**Comment by cgaboret** [comment]
Hello, 
I've recently upgraded from 1.3 to 1.4 and I read the same thing in catalina.out: 
[http-bio-8080-exec-5] ERROR o.a.g.s.GuacamoleHTTPTunnelServlet - HTTP tunnel request failed: java.net.ConnectException: Connection refused (Connection refused)

guacd-hostname: 127.0.0.1
guacd-port: 4822
in /etc/guacamole/guacamole.properties doesn't change anything. Following https://www.mail-archive.com/user@guacamole.apache.org/msg09263.html I also create a /etc/guacamole/guacd.conf with no success. 

Do you have an idea ? 

Thanks in advance,
Christophe.

**Comment by gokhangulgezen** [comment]
Hi, 
I am having the same issue, I just installed guacamole 1.4, but getting "ERROR o.a.g.s.GuacamoleHTTPTunnelServlet - HTTP tunnel request failed: java.net.ConnectException: Connection refused (Connection refused)" error message with each connection attempt.

I have no idea what might be the problem is?
Thanks in advance.

**Comment by JohnDamay** [comment]
Hi,
Was also moving to 1.4 on a new server. But in fact these error was due to IPV6 / IPV4 misundertsanding (not very clear why...).
So solution for me was to create the guacd.conf file in /etc/guacamole/ to force bind-host to 127.0.0.1 and not localhost ( :: 1).

The clue was that i get same error no matter guacd is running or not... so clearly nothing was listening!!

Regards,
Jean.

**Comment by KulawyPajak** [comment]
Hi, i have the same problem on FreeBSD 12.2 - SOLUTION:
Change "localhost" hostname in:
/usr/local/etc/guacamole-client/guacamole.properties
to "example"
guacd-hostname: 192.168.10.10
next: /usr/local/etc/guacamole-server/guacd.conf
[server]
bind_host = 192.168.10.10
Check /etc/guacamole/guacamole.properties i have link:
guacd-hostname: 192.168.10.10
Restart:
/usr/local/etc/rc.d/guacd restart
/usr/local/etc/rc.d/tomcat9 restart

with name "localhost" i have:
11:01:48.010 [http-nio-8085-exec-3] DEBUG o.a.g.s.GuacamoleHTTPTunnelServlet - Internal error in HTTP tunnel.
I hope it will be useful to someone else - it works for me;)

**Comment by gabrielhxcx** [comment]
Hi guys,

I fixed the problem with solution below John Damay, I edited my /etc/hosts removing the name localhost from ::1 line, restart the service and I can connect with RDP.

**Comment by Gabriel-1023** [comment]
What if the same problem on docker container 😊
