### ISSUE TITLE
Configure RDP connection to windows 7/10 with more than one user

### ISSUE THREAD

**Issue by nwf00** [MysticRyuujin/guac-install#75]
Hi I'n new on Apache Guacamole. I installed Guacamole 1.0.0 with mysql and nginx in Ubuntu 18.04 

I need to know how to configure a RDP connection for Windows 7 or windows 10 with more than one user, Ex; windows 10 with 2 users ( Administrator and User01). It is possible? or I need to create as many connection as users? When I configure a RDP connection I can't leave User and pass blank so as to enter manually the credentials.  Can any one tell me if this is possible? 

Thanks 
NWF

**Comment by bmullan** [comment]
Windows 7 or 10 are not Windows Servers.  With Win7 I believe you can by
default only have 1 user at a time logged in via RDP.

There are tools you can use to do this for Win7 but they may violate
Microsoft's EULA so I won't mention them specifically but a google search
will point out some

With Windows Server you would still need to purchase CALS or whatever they
are called today to permit N number of concurrent users.

But with Windows 10 there may be other options.  Do a google search using:

"multi user windows 10 remote desktop"

**Comment by nwf00** [comment]
Hi bmullan,

Perhaps I didn't explain myself very well, I know that with win 7 and 10 you can't connect simultaneously.

I have a 2 virtual Machines one with windows 7 and the other with windows 10. Both windows have 2 user ( Administrator and USER01). When I configure the RDP connection in Apache Guacamole there are two parameters ( Username and Password) so I want to know if there is a way to configure one connection in Guacamole and be able to enter with one user or the other ( I not using both users simultaneously) to leave the User and password in blank and choose a user. In the image below I configure a connection RDP in windows 7 pro and left the user name and pass blank and when I connect I can choose the user.

![image](https://user-images.githubusercontent.com/25247256/53108136-3ddd2800-3515-11e9-9867-fb54a8173806.png)

Is there a way to do the same with Windows 10, with Win 10 I can't leave the username and password in blank, it wont connect. 

![image](https://user-images.githubusercontent.com/25247256/53108594-0fac1800-3516-11e9-99fd-6500fc6ca6bc.png)

Is there a way to configure Guacamole RDP to connect to windows 10 and choose a user?

Thanks for the help

**Comment by bmullan** [comment]
Oh... okay, yes  I misunderstood what you wanted to do.
I assume you are running Guacamole on a Linux VM/server/Desktop?
and if so then you are using xrdp on that linux to connect to the Windows 7 or Windows 10 VMs?

Now I still may not be understanding exactly what you are doing but...

ASSUMING - the Windows UserID and Password are the same as the Guacamole UserID and Password.

In guacamole you could create 4 connections, two for your Win7 and two for Win10.
one each:
win7Admin
win10Admin
and
win7
win10

In all Four Connections...

In the Connection "field" under Authentication labeled "username" put:
${GUAC_USERNAME}

In the Connection "field" under Authentication labeled "password" put:
${GUAC_PASSWORD}

Guacamole will show you "*" for each letter you type in the password field so type carefully.

In only the win7Admin and in the win10Admin check the Connection field box labeled "console"
reference:   http://guacamole.apache.org/doc/gug/configuring-guacamole.html#rdp
                   and look under Session Settings - RDP for "console" where it says:
"console  --  If set to "true", you will be connected to the console (admin) session of the RDP server."

Save each connection.

Edit each Guacamole USER and make sure they are given access to all 4 Connections. 

Now when your User logs into Guacamole they will see 4 Guacamole Connections:

Win7
win7Admin
Win10
win10Admin

All they will have to doe is click on whichever connection they want and because you setup the connections using those special fields

${GUAC_USERNAME}
${GUAC_PASSWORD}

they won't even get prompted for login/password by windows because Guacamole will pass their UserName and Password to XRDP which will use them to log into the windows VMs.

This way the user's don't have to enter their UserID and Password twice.

For reference to the above "Guacamole Parameter Tokens" see:
http://guacamole.apache.org/doc/gug/configuring-guacamole.html#parameter-tokens

Hope that helps?   All this is doing is let the user log into Guacamole & "choose" there which connection to make:  Win7 normal user, Win7 Admin Console,  Win10 normal user, Win10 Admin Console
