### ISSUE TITLE
Script for Debian - Request

### ISSUE THREAD

**Issue by joshbgosh10592** [MysticRyuujin/guac-install#8]
Any chance you could post a version for Debian, since Ubuntu is Debian based? Running the script on Debian fails during the install of dependencies, and from there pretty much blows up. I don't know enough about the differences to modify...

**Comment by MysticRyuujin** [comment]
@joshbgosh10592 - Check out [Install Guide Dependencies](https://guacamole.incubator.apache.org/doc/0.9.12-incubating/gug/installing-guacamole.html)

If you look at that guide it lists all of the required dependencies for Debian. It literally says:

> "Debian / Ubuntu package"

I'm like 90% sure that the packages listed are for Debian, because to get it to work on Ubuntu I had to rename a few of the packages listed...

So what I would do is copy and run this line from my script:

`apt-get -y install build-essential libcairo2-dev libjpeg-turbo8-dev libpng12-dev libossp-uuid-dev libavcodec-dev libavutil-dev \
libswscale-dev libfreerdp-dev libpango1.0-dev libssh2-1-dev libtelnet-dev libvncserver-dev libpulse-dev libssl-dev \
libvorbis-dev libwebp-dev mysql-server mysql-client mysql-common mysql-utilities tomcat8 freerdp ghostscript jq wget curl`

When you do that, it will no doubt error out and when it errors out it will say that it couldn't find "package-name" then all you have to do is figure out what the package is called on Debian, it's probably the original name listed on the link I just provided :)

**Comment by MysticRyuujin** [comment]
Also, if you tell me what packages that you replace to get it to work I can probably modify the script to work for either OS

**Comment by joshbgosh10592** [comment]
Hey there!
One of the packages that throws an error is lib-jpeg-turbo. The script calls for 'libjpeg-turbo8-dev'. The dependencies calls for libjpeg62-turbo-dev, so I'm not sure if maybe that would make it universal for both Ubuntu and Debian?
I ran just the dependencies install (with the substitution) and they succeeded. Then, I changed the 'libjpeg-turbo8-dev' to 'libjpeg62-turbo-dev' in the script and ran it. 
Install succeeded.

**Comment by MysticRyuujin** [comment]
So the only dependency change is libjpeg and everything else worked
correctly? That seems like an easy fix.

On Jul 27, 2017 9:16 AM, "joshbgosh10592" <notifications@github.com> wrote:

Hey there!
One of the packages that throws an error is lib-jpeg-turbo. The script
calls for 'libjpeg-turbo8-dev'. The dependencies calls for
libjpeg62-turbo-dev, so I'm not sure if maybe that would make it universal
for both Ubuntu and Debian?
I ran just the dependencies install (with the substitution) and they
succeeded. Then, I changed the 'libjpeg-turbo8-dev' to
'libjpeg62-turbo-dev' in the script and ran it.
Install succeeded.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/MysticRyuujin/guac-install/issues/8#issuecomment-318375247>,
or mute the thread

**Comment by joshbgosh10592** [comment]
Yup! That's the only change needed. It looks like if you just change libjpeg-turbo8-dev to libjpeg62-turbo-dev, it should be compatible with both.
Also, thank you very much for building this script. Guac is awesome, but such a pain in the rear to get up and running...

**Comment by MysticRyuujin** [comment]
Fixed
